baseURL = "https://mlinreallife.github.io"
languageCode = "en-uk"
title = "Machine learning in real life"
theme = "hyde-hyde"
DefaultContentLanguage = "en"
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-uk"
    weight = 1

[params.social]
  gravatar = "nastasia.saby@gmail.com"
  twitter = "saby_nastasia"

[params]
    author="Nastasia Saby"
    description="Nastasia Saby"
    mainSections = ["posts"]
    keywords = ["machine learning", "models", "data science", "production", "engineering", "ml"]

    ## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Press reviews"
    identifier = "press_reviews"
    weight = 200
    url = "/press_reviews/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"

